# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenTax' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenTax
  pod 'SnapKit'
  pod 'Closures'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'OpenTaxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenTaxUITests' do
    # Pods for testing
  end

end
