# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeniorDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeniorDesign
  pod 'Parse'
  pod 'ActivityIndicatorView'

  target 'SeniorDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeniorDesignUITests' do
    # Pods for testing
  end

end
